/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AttribSelector.java
 *
 * Created on 10/03/2011, 01:55:25
 */

package attributeselection;

import java.util.ArrayList;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Renato R O da Silva
 */
public class AttributesSelector extends javax.swing.JDialog {

    private int buttonClicked = -1;
    public static final int BTN_OK = 0;
    public static final int BTN_CANCEL = 1;


    /** Creates new form AttribSelector */
    public AttributesSelector(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }


    public int display() {
        
        this.setVisible(true);
        return buttonClicked;
    }

    public ArrayList<String> getSelectedAttributes() {

        ArrayList<String> selectedElementsList = new ArrayList();
        ListSelectionModel selectionModel = jTable1.getSelectionModel();
        int elementsCount = jTable1.getRowCount();

        for (int i = 0; i < elementsCount; i++) {
            if (selectionModel.isSelectedIndex(i)) {
                selectedElementsList.add((String)jTable1.getValueAt(i, 0));
            }
        }

        return selectedElementsList;
    }

    public void refreshTableValues(ArrayList<String> attributesList, ArrayList<String> selectedAttributesList) {
        boolean selectedAttributes[] = new boolean[attributesList.size()];

        if (selectedAttributesList == null)
            selectedAttributesList = attributesList;

        for (int i = 0; i < attributesList.size(); i++)
            if (selectedAttributesList.indexOf(attributesList.get(i)) == -1)
                selectedAttributes[i] = false;
            else {
                selectedAttributes[i] = true;
            }

        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();

        for (int i = 0; i < attributesList.size(); i++) {
            model.addRow(new Object[] {attributesList.get(i)});
        }

        ListSelectionModel selectionModel = jTable1.getSelectionModel();
        selectionModel.clearSelection();


        for (int i = 0; i < selectedAttributesList.size(); i++) {
            selectionModel.addSelectionInterval(attributesList.indexOf(selectedAttributesList.get(i)), attributesList.indexOf(selectedAttributesList.get(i)));
        }

    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Attribute"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        this.buttonClicked = BTN_OK;
        this.setVisible(false);
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        this.buttonClicked = BTN_CANCEL;
        this.setVisible(false);
    }                                        

    /**
    * @param args the command line arguments
    */
   /*  public static void main(String args[]) {
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AttributesSelector dialog = new AttributesSelector(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration                   

}
