/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package attributeselection;

import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author aurea
 */
public class NumberThreads extends javax.swing.JDialog {

    private int buttonClicked = -1;
    public static final int BTN_OK = 0;
    public static final int BTN_CANCEL = 1;
    public Integer selectedNumberThreads = 1;

    /**
     * Creates new form NumberThreads
     *
     * @param parent
     * @param modal
     */
    public NumberThreads(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public int display() {
        this.setVisible(true);
        return buttonClicked;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numberThreadsLabel = new javax.swing.JLabel();
        numberThreadsComboBox = new javax.swing.JComboBox();
        okNumberThreadsButton = new javax.swing.JButton();
        cancelNumberThreadsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        numberThreadsLabel.setText("# Threads:");

        numberThreadsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberThreadsComboBoxActionPerformed(evt);
            }
        });

        okNumberThreadsButton.setText("OK");
        okNumberThreadsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okNumberThreadsButtonActionPerformed(evt);
            }
        });

        cancelNumberThreadsButton.setText("Cancel");
        cancelNumberThreadsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelNumberThreadsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(numberThreadsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(okNumberThreadsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numberThreadsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(cancelNumberThreadsButton)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberThreadsLabel)
                    .addComponent(numberThreadsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okNumberThreadsButton)
                    .addComponent(cancelNumberThreadsButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okNumberThreadsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okNumberThreadsButtonActionPerformed
        this.buttonClicked = BTN_OK;
        this.setVisible(false);
    }//GEN-LAST:event_okNumberThreadsButtonActionPerformed

    private void cancelNumberThreadsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelNumberThreadsButtonActionPerformed
        this.buttonClicked = BTN_CANCEL;
        this.setVisible(false);
    }//GEN-LAST:event_cancelNumberThreadsButtonActionPerformed

    private void numberThreadsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberThreadsComboBoxActionPerformed
        this.selectedNumberThreads = Integer.valueOf(this.numberThreadsComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_numberThreadsComboBoxActionPerformed

      public void refreshNumberThreads(Integer numberThread) {
        Integer[] strThreads = new Integer[100];
        for(int i=0;i<100; i++)
        {
            strThreads[i]=i+1;
        }
        
        
        DefaultComboBoxModel threadsModel = new DefaultComboBoxModel(strThreads);
        this.numberThreadsComboBox.setModel(threadsModel);
        this.numberThreadsComboBox.setSelectedItem(numberThread);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NumberThreads.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                NumberThreads dialog = new NumberThreads(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelNumberThreadsButton;
    private javax.swing.JComboBox numberThreadsComboBox;
    private javax.swing.JLabel numberThreadsLabel;
    private javax.swing.JButton okNumberThreadsButton;
    // End of variables declaration//GEN-END:variables
}
